# Build stage
FROM golang:1.24-alpine AS builder

WORKDIR /usr/src/user-database

# Install build dependencies
RUN apk add --no-cache git

# Download dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copy source code
COPY . .

# Build the application
RUN CGO_ENABLED=0 GOOS=linux go build -o /user-database cmd/user-database/main.go

# Final stage
FROM alpine:latest

# Install runtime dependencies
RUN apk --no-cache add ca-certificates openssl

WORKDIR /root/

# Copy the binary from builder
COPY --from=builder /user-database .

# Create self-signed certificates for development
RUN openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365 -nodes -subj "/C=US/ST=State/L=City/O=Organization/CN=localhost"

# Update CA certificates
RUN update-ca-certificates

# Expose the port the app runs on
EXPOSE 8082/tcp

COPY .env .
# Command to run the executable
CMD ["./user-database"]
