version: '3.7'

services:
  telegram-bot-api:
    image: aiogram/telegram-bot-api:latest
    container_name: telegram-bot-api-local
    environment:
      TELEGRAM_API_ID: "your api id"
      TELEGRAM_API_HASH: "your hash"
    volumes:
      - telegram-bot-api-data:/var/lib/telegram-bot-api
    ports:
      - "8081:8081"

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: your user
      POSTGRES_PASSWORD: your password
      POSTGRES_DB: your db
    ports:
      - "5432:5432"

  tg-database:
    image: tg-users-database:latest
    container_name: tg-database
    depends_on:
      - db
    ports:
      - "8082:8082"

  telegram-bot:
    image: telegram-bot:latest
    container_name: telegram-bot
    environment:
      - DOWNLOAD_PATH=/download
    volumes:
      - .:/usr/src/telegram-bot
    depends_on:
      - telegram-bot-api
      - tg-database
    ports:
      - "8080:8080"


volumes:
  telegram-bot-api-data:
